### ISSUE TITLE
Stopping a client nicely: are lifecycle hooks possible?

### ISSUE THREAD

**Issue by cgavriluta** [AIT-Lablink/lablink-core-java#2]
@kazmijawad, @ewidl is there an approach for stopping a client cleanly? The Redis/Opal-RT client starts a pool of threads for reading data from Redis. How do I hook the closing of the thread pool to the closing of the client?

I think having the possibility to add lifecycle hooks for the clients could prove useful on the long run. What do you think?

**Comment by kazmijawad** [comment]
Setting up such a hook would be possible and a good feature also. As discussed today, it will be considered with the additional features planned to be rolled out in the coming months.
